namespace KhStructs.Kh2.Object.Entry;

public enum ObjectType : byte {
    Player = 0x0,
    PartyMember = 0x1,
    Npc = 0x2,
    Boss = 0x3,
    NormalEnemy = 0x4,
    Weapon = 0x5,
    ArdPlaceholder = 0x6,
    SavePoint = 0x7,
    Field = 0x8,
    Partner = 0x9,
    Chest = 0xA,
    Moogle = 0xB,
    LargeBoss = 0xC,
    GObj = 0xD,
    PauseMenuDummy = 0xE,
    Rtn = 0xF,
    Minigame = 0x10,
    WorldMap = 0x11,
    PrizeBox = 0x12,
    Summon = 0x13,
    Shop = 0x14,
    LNormalEnemy = 0x15,
    CrowdSpawner = 0x16,
    EObj = 0x17,
    PuzzlePiece = 0x18,
}
